
project_id = "qdslhxpjnciozacwfyix"

[functions.send-acceptance-email]
verify_jwt = false

[functions.send-application-confirmation]
verify_jwt = false

[functions.send-appointment-confirmation]
verify_jwt = false

[functions.send-employment-contract-invitation]
verify_jwt = false
