// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdslhxpjnciozacwfyix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkc2xoeHBqbmNpb3phY3dmeWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzkyNzAsImV4cCI6MjA2NDcxNTI3MH0.ci4QfZYn3aVQ4wZfXGZs3z9Iq_QGFgcXr3Vjgjt1Drw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);